/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.31
</auto-generated>
------------------------------------------------------------------------------ */

using SFDec2022.Mvc.Models;
using System;
using System.ComponentModel;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;

namespace SFDec2022.Mvc.Controllers
{
    public enum Enumeration
    {
        Value1,
        Value2,
        Value3
    }
    [ControllerToolboxItem(Name = "EliseWidget", Title = "Elise Widget", SectionName = "SFDev2022")]
	public class EliseWidgetController : Controller, IPersonalizable
	{
		// GET: EliseWidget
		public ActionResult Index()
		{
			var model = new EliseWidgetModel();
			model.Message = this.Message;
            model.Number = this.Number;
            return View("Johnny", model);
		}

        public ActionResult Kyle()
        {
            return View();
        }

        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

        public string Message { get; set; }
        public bool Flag { get; set; }
        public Enumeration Enum { get; set; }
        [Browsable(false)]
        public int Number { get; set; }
        public DateTime MyDate { get; set; }

    }
}