/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.31
</auto-generated>
------------------------------------------------------------------------------ */

using SFDec2022.Mvc.Controllers;
using System;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;

namespace SFDec2022.Mvc.Models
{
	public class EliseWidgetModel
	{
        public string Message { get; set; }
        public bool Flag { get; set; }
        public Enumeration Enum { get; set; }
        public int Number { get; set; }
        public DateTime MyDate { get; set; }
    }
}