/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.31
</auto-generated>
------------------------------------------------------------------------------ */

using SFDec2022.Mvc.Models;
using System.ComponentModel;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;

namespace SFDec2022.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "AdamWidget", Title = "Adam Widget", SectionName = "SFDev2022")]
	public class AdamWidgetController : Controller, IPersonalizable
	{
		// GET: AdamWidget
		public ActionResult Index()
		{
			var model = new AdamWidgetModel();
			model.Message = this.Message;
			return View("Index", model);
		}
		
        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

		[Category("Main")]
		public string Message { get; set; }
	}
}